line_length: 150
type_body_length: 500
function_parameter_count: 6
file_length: 500
cyclomatic_complexity: 20
function_body_length: 80
variable_name: 2

force_try:
  severity: warning # explicitly

excluded:
  - Pods
