# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "ea993f48-e61c-48dc-81e9-92e9dcf3aadf"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  cocoapods

  # build your iOS app
  gym(
    scheme: "lfg"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "67a4457241473bb26a54ebd2cf8dce0c774f5a06",
    build_secret: "dfe05ccaca800d3ffd13921e8190e092e1c8632a4fbb9712431ee727eba6f1f8"
  )
end
